"""Add Google credentials table

Revision ID: c2345dc890ef
Revises: b24223c142f6
Create Date: 2025-06-03 06:47:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2345dc890ef'
down_revision = 'b24223c142f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_uri', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_google_credentials_id'), 'google_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_google_credentials_user_id'), 'google_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_credentials_user_id'), table_name='google_credentials')
    op.drop_index(op.f('ix_google_credentials_id'), table_name='google_credentials')
    op.drop_table('google_credentials')
    # ### end Alembic commands ###